apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: "{{ k8s_namespace }}"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  # Allow all ingress traffic from kube-system namespace to allow
  # connections from CoreDNS and Calico
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
  # Allow all egress traffic to kube-system namespace to allow
  # connections to CoreDNS and Calico
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
